/*
** This file was automatically generated by fdtrans.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/guigfx.h>
#include <proto/guigfx.h>

#include <graphics/rastport.h>
#include <graphics/view.h>

STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

        return (ULONG) Self->Open(0);
}
struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

        return (ULONG) Self->Close();
}
struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
        return 0UL;
}
struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
        return 0UL;
}
struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };


static APTR stub_MakePictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->MakePictureA(
                (APTR)regarray[8],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_MakePictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_MakePictureAPPC };

static APTR stub_LoadPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->LoadPictureA(
                (STRPTR)regarray[8],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_LoadPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LoadPictureAPPC };

static APTR stub_ReadPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->ReadPictureA(
                (struct RastPort *)regarray[8],
                (struct ColorMap *)regarray[9],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (UWORD)regarray[2],
                (UWORD)regarray[3],
                (struct TagItem *)regarray[10]);
}
struct EmuTrap stub_ReadPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ReadPictureAPPC };

static APTR stub_ClonePictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->ClonePictureA(
                (APTR)regarray[8],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_ClonePictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClonePictureAPPC };

static void stub_DeletePicturePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->DeletePicture(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_DeletePicture = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DeletePicturePPC };

static BOOL stub_UpdatePicturePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->UpdatePicture(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_UpdatePicture = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_UpdatePicturePPC };

static APTR stub_AddPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->AddPictureA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_AddPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_AddPictureAPPC };

static APTR stub_AddPaletteAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->AddPaletteA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_AddPaletteA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_AddPaletteAPPC };

static APTR stub_AddPixelArrayAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->AddPixelArrayA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_AddPixelArrayA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_AddPixelArrayAPPC };

static void stub_RemColorHandlePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->RemColorHandle(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_RemColorHandle = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_RemColorHandlePPC };

static APTR stub_CreatePenShareMapAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->CreatePenShareMapA(
                (struct TagItem *)regarray[8]
        );
}
struct EmuTrap stub_CreatePenShareMapA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CreatePenShareMapAPPC };

static void stub_DeletePenShareMapPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->DeletePenShareMap(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_DeletePenShareMap = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DeletePenShareMapPPC };

static APTR stub_ObtainDrawHandleAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->ObtainDrawHandleA(
                (APTR)regarray[8],
                (struct RastPort *)regarray[9],
                (struct ColorMap *)regarray[10],
                (struct TagItem *)regarray[11]
        );
}
struct EmuTrap stub_ObtainDrawHandleA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ObtainDrawHandleAPPC };

static void stub_ReleaseDrawHandlePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->ReleaseDrawHandle(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_ReleaseDrawHandle = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ReleaseDrawHandlePPC };

static BOOL stub_DrawPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->DrawPictureA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_DrawPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DrawPictureAPPC };

static BOOL stub_MapPaletteAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->MapPaletteA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (UBYTE *)regarray[10],
                (struct TagItem *)regarray[11]
        );
}
struct EmuTrap stub_MapPaletteA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_MapPaletteAPPC };

static LONG stub_MapPenAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->MapPenA(
                (APTR)regarray[8],
                (ULONG)regarray[9],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_MapPenA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_MapPenAPPC };

static struct BitMap * stub_CreatePictureBitMapAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->CreatePictureBitMapA(
                (APTR)regarray[8],
                (APTR)regarray[9],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_CreatePictureBitMapA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CreatePictureBitMapAPPC };

static ULONG stub_DoPictureMethodAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->DoPictureMethodA(
                (APTR)regarray[8],
                (ULONG)regarray[0],
                (ULONG *)regarray[9]
        );
}
struct EmuTrap stub_DoPictureMethodA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DoPictureMethodAPPC };

static ULONG stub_GetPictureAttrsAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->GetPictureAttrsA(
                (APTR)regarray[8],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_GetPictureAttrsA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_GetPictureAttrsAPPC };

static ULONG stub_LockPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->LockPictureA(
                (APTR)regarray[8],
                (ULONG)regarray[0],
                (ULONG *)regarray[9]
        );
}
struct EmuTrap stub_LockPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_LockPictureAPPC };

static void stub_UnLockPicturePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->UnLockPicture(
                (APTR)regarray[8],
                (ULONG)regarray[0]
        );
}
struct EmuTrap stub_UnLockPicture = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_UnLockPicturePPC };

static BOOL stub_IsPictureAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->IsPictureA(
                (char *)regarray[8],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_IsPictureA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_IsPictureAPPC };

static APTR stub_CreateDirectDrawHandleAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->CreateDirectDrawHandleA(
                (APTR)regarray[8],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (UWORD)regarray[2],
                (UWORD)regarray[3],
                (struct TagItem *)regarray[9]
        );
}
struct EmuTrap stub_CreateDirectDrawHandleA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CreateDirectDrawHandleAPPC };

static void stub_DeleteDirectDrawHandlePPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        Self->DeleteDirectDrawHandle(
                (APTR)regarray[8]
        );
}
struct EmuTrap stub_DeleteDirectDrawHandle = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DeleteDirectDrawHandlePPC };

static BOOL stub_DirectDrawTrueColorAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->DirectDrawTrueColorA(
                (APTR)regarray[8],
                (ULONG *)regarray[9],
                (UWORD)regarray[0],
                (UWORD)regarray[1],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_DirectDrawTrueColorA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_DirectDrawTrueColorAPPC };

static BOOL stub_CreatePictureMaskAPPC(ULONG *regarray)
{
        struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
        struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
        struct GuiGFXIFace *Self = (struct GuiGFXIFace *) ExtLib->MainIFace;

        return Self->CreatePictureMaskA(
                (APTR)regarray[8],
                (UBYTE *)regarray[9],
                (UWORD)regarray[0],
                (struct TagItem *)regarray[10]
        );
}
struct EmuTrap stub_CreatePictureMaskA = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_CreatePictureMaskAPPC };

ULONG VecTable68K[] = {
        (ULONG)&stub_Open,
        (ULONG)&stub_Close,
        (ULONG)&stub_Expunge,
        (ULONG)&stub_Reserved,
        (ULONG)&stub_MakePictureA,
        (ULONG)&stub_LoadPictureA,
        (ULONG)&stub_ReadPictureA,
        (ULONG)&stub_ClonePictureA,
        (ULONG)&stub_DeletePicture,
        (ULONG)&stub_UpdatePicture,
        (ULONG)&stub_AddPictureA,
        (ULONG)&stub_AddPaletteA,
        (ULONG)&stub_AddPixelArrayA,
        (ULONG)&stub_RemColorHandle,
        (ULONG)&stub_CreatePenShareMapA,
        (ULONG)&stub_DeletePenShareMap,
        (ULONG)&stub_ObtainDrawHandleA,
        (ULONG)&stub_ReleaseDrawHandle,
        (ULONG)&stub_DrawPictureA,
        (ULONG)&stub_MapPaletteA,
        (ULONG)&stub_MapPenA,
        (ULONG)&stub_CreatePictureBitMapA,
        (ULONG)&stub_DoPictureMethodA,
        (ULONG)&stub_GetPictureAttrsA,
        (ULONG)&stub_LockPictureA,
        (ULONG)&stub_UnLockPicture,
        (ULONG)&stub_IsPictureA,
        (ULONG)&stub_CreateDirectDrawHandleA,
        (ULONG)&stub_DeleteDirectDrawHandle,
        (ULONG)&stub_DirectDrawTrueColorA,
        (ULONG)&stub_CreatePictureMaskA,
        (ULONG)-1
};

